/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	extendingresscontrollerv1alpha1 "k8s.io/extendingress-controller/pkg/apis/extendingresscontroller/v1alpha1"
	versioned "k8s.io/extendingress-controller/pkg/client/clientset/versioned"
	internalinterfaces "k8s.io/extendingress-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "k8s.io/extendingress-controller/pkg/client/listers/extendingresscontroller/v1alpha1"
)

// ExtendIngressInformer provides access to a shared informer and lister for
// ExtendIngresses.
type ExtendIngressInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ExtendIngressLister
}

type extendIngressInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewExtendIngressInformer constructs a new informer for ExtendIngress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewExtendIngressInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredExtendIngressInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredExtendIngressInformer constructs a new informer for ExtendIngress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredExtendIngressInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExtendingresscontrollerV1alpha1().ExtendIngresses(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExtendingresscontrollerV1alpha1().ExtendIngresses(namespace).Watch(options)
			},
		},
		&extendingresscontrollerv1alpha1.ExtendIngress{},
		resyncPeriod,
		indexers,
	)
}

func (f *extendIngressInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredExtendIngressInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *extendIngressInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&extendingresscontrollerv1alpha1.ExtendIngress{}, f.defaultInformer)
}

func (f *extendIngressInformer) Lister() v1alpha1.ExtendIngressLister {
	return v1alpha1.NewExtendIngressLister(f.Informer().GetIndexer())
}
