/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "k8s.io/extendingress-controller/pkg/apis/extendingresscontroller/v1alpha1"
	scheme "k8s.io/extendingress-controller/pkg/client/clientset/versioned/scheme"
)

// ExtendIngressesGetter has a method to return a ExtendIngressInterface.
// A group's client should implement this interface.
type ExtendIngressesGetter interface {
	ExtendIngresses(namespace string) ExtendIngressInterface
}

// ExtendIngressInterface has methods to work with ExtendIngress resources.
type ExtendIngressInterface interface {
	Create(*v1alpha1.ExtendIngress) (*v1alpha1.ExtendIngress, error)
	Update(*v1alpha1.ExtendIngress) (*v1alpha1.ExtendIngress, error)
	UpdateStatus(*v1alpha1.ExtendIngress) (*v1alpha1.ExtendIngress, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ExtendIngress, error)
	List(opts v1.ListOptions) (*v1alpha1.ExtendIngressList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ExtendIngress, err error)
	ExtendIngressExpansion
}

// extendIngresses implements ExtendIngressInterface
type extendIngresses struct {
	client rest.Interface
	ns     string
}

// newExtendIngresses returns a ExtendIngresses
func newExtendIngresses(c *ExtendingresscontrollerV1alpha1Client, namespace string) *extendIngresses {
	return &extendIngresses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the extendIngress, and returns the corresponding extendIngress object, and an error if there is any.
func (c *extendIngresses) Get(name string, options v1.GetOptions) (result *v1alpha1.ExtendIngress, err error) {
	result = &v1alpha1.ExtendIngress{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("extendingresses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ExtendIngresses that match those selectors.
func (c *extendIngresses) List(opts v1.ListOptions) (result *v1alpha1.ExtendIngressList, err error) {
	result = &v1alpha1.ExtendIngressList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("extendingresses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested extendIngresses.
func (c *extendIngresses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("extendingresses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a extendIngress and creates it.  Returns the server's representation of the extendIngress, and an error, if there is any.
func (c *extendIngresses) Create(extendIngress *v1alpha1.ExtendIngress) (result *v1alpha1.ExtendIngress, err error) {
	result = &v1alpha1.ExtendIngress{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("extendingresses").
		Body(extendIngress).
		Do().
		Into(result)
	return
}

// Update takes the representation of a extendIngress and updates it. Returns the server's representation of the extendIngress, and an error, if there is any.
func (c *extendIngresses) Update(extendIngress *v1alpha1.ExtendIngress) (result *v1alpha1.ExtendIngress, err error) {
	result = &v1alpha1.ExtendIngress{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("extendingresses").
		Name(extendIngress.Name).
		Body(extendIngress).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *extendIngresses) UpdateStatus(extendIngress *v1alpha1.ExtendIngress) (result *v1alpha1.ExtendIngress, err error) {
	result = &v1alpha1.ExtendIngress{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("extendingresses").
		Name(extendIngress.Name).
		SubResource("status").
		Body(extendIngress).
		Do().
		Into(result)
	return
}

// Delete takes name of the extendIngress and deletes it. Returns an error if one occurs.
func (c *extendIngresses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("extendingresses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *extendIngresses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("extendingresses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched extendIngress.
func (c *extendIngresses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ExtendIngress, err error) {
	result = &v1alpha1.ExtendIngress{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("extendingresses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
