/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "k8s.io/extendingress-controller/pkg/apis/extendingresscontroller/v1alpha1"
)

// FakeExtendIngresses implements ExtendIngressInterface
type FakeExtendIngresses struct {
	Fake *FakeExtendingresscontrollerV1alpha1
	ns   string
}

var extendingressesResource = schema.GroupVersionResource{Group: "extendingresscontroller.k8s.io", Version: "v1alpha1", Resource: "extendingresses"}

var extendingressesKind = schema.GroupVersionKind{Group: "extendingresscontroller.k8s.io", Version: "v1alpha1", Kind: "ExtendIngress"}

// Get takes name of the extendIngress, and returns the corresponding extendIngress object, and an error if there is any.
func (c *FakeExtendIngresses) Get(name string, options v1.GetOptions) (result *v1alpha1.ExtendIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(extendingressesResource, c.ns, name), &v1alpha1.ExtendIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendIngress), err
}

// List takes label and field selectors, and returns the list of ExtendIngresses that match those selectors.
func (c *FakeExtendIngresses) List(opts v1.ListOptions) (result *v1alpha1.ExtendIngressList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(extendingressesResource, extendingressesKind, c.ns, opts), &v1alpha1.ExtendIngressList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ExtendIngressList{ListMeta: obj.(*v1alpha1.ExtendIngressList).ListMeta}
	for _, item := range obj.(*v1alpha1.ExtendIngressList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested extendIngresses.
func (c *FakeExtendIngresses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(extendingressesResource, c.ns, opts))

}

// Create takes the representation of a extendIngress and creates it.  Returns the server's representation of the extendIngress, and an error, if there is any.
func (c *FakeExtendIngresses) Create(extendIngress *v1alpha1.ExtendIngress) (result *v1alpha1.ExtendIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(extendingressesResource, c.ns, extendIngress), &v1alpha1.ExtendIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendIngress), err
}

// Update takes the representation of a extendIngress and updates it. Returns the server's representation of the extendIngress, and an error, if there is any.
func (c *FakeExtendIngresses) Update(extendIngress *v1alpha1.ExtendIngress) (result *v1alpha1.ExtendIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(extendingressesResource, c.ns, extendIngress), &v1alpha1.ExtendIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendIngress), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeExtendIngresses) UpdateStatus(extendIngress *v1alpha1.ExtendIngress) (*v1alpha1.ExtendIngress, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(extendingressesResource, "status", c.ns, extendIngress), &v1alpha1.ExtendIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendIngress), err
}

// Delete takes name of the extendIngress and deletes it. Returns an error if one occurs.
func (c *FakeExtendIngresses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(extendingressesResource, c.ns, name), &v1alpha1.ExtendIngress{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExtendIngresses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(extendingressesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ExtendIngressList{})
	return err
}

// Patch applies the patch and returns the patched extendIngress.
func (c *FakeExtendIngresses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ExtendIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(extendingressesResource, c.ns, name, data, subresources...), &v1alpha1.ExtendIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendIngress), err
}
